spring:
  profiles:
    active: dev
  server:
    port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=anonymization_data
    username: localuser
    password: localpass
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    changelog: db/db.changelog-master.yml