--liquibase formatted sql

--changeset user:1
CREATE TABLE IF NOT EXISTS PERSON(
    ID         INT          NOT NULL PRIMARY KEY,
    NUME       VARCHAR(30)  NOT NULL,
    PRENUME    VARCHAR(50)  NOT NULL,
    CNP        VARCHAR(20)  NOT NULL,
    VARSTA     VARCHAR(3)   NOT NULL,
    COD_POSTAL VARCHAR(15)  NOT NULL,
    TELEFON    VARCHAR(20)  NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL
);
--rollback DROP TABLE PERSON;