--liquibase formatted sql

--changeset user:1
CREATE TABLE IF NOT EXISTS ANONYMIZED_PERSON(
    ID UUID NOT NULL PRIMARY KEY,
    NUME VARCHAR(30) NOT NULL,
    PRENUME VARCHAR(50) NOT NULL,
    CNP VARCHAR(13) NOT NULL,
    DATA_NASTERII DATE NOT NULL,
    ADRESA VARCHAR(255) NOT NULL,
    TELEFON VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);
--rollback DROP TABLE ANONYMIZED_PERSON;